### PR TITLE
new url for CV examples

### PR DESCRIPTION
**Pull request by cderv**
See #72

@dktanwar are you still willing to share your example ? 

I updated the url and also added the source link. 

Thanks for sharing

---
This change is [Reviewable](https://reviewable.io/reviews/rstudio/pagedown/123)

### CODE REVIEW

**Comment by dktanwar** [comment]
Yes, I am!

**Comment by dktanwar** [comment]
Hi @cderv 

Just wanted to let you know that I am updating my website on GitHub with Academic Hugo theme. Due to this, the link to my CV might not work now. I will update you once I am done (most probably early next week).

**Comment by yihui** [comment]
Before Github Pages really supports 301 redirects, I strongly recommend that you use Netlify: https://yihui.name/en/2017/06/netlify-instead-of-github-pages/ With 301 redirects, there is no need to update links. All links could and should be automatically redirected.

**Comment by dktanwar** [comment]
Hi @yihui 

Thank you for the recommendation. I will read about it and try to have my website there.

**Pull request merged**
