### PR TITLE
Links to footnotes-Update for Pandoc 2.3.1

### PR DESCRIPTION
**Pull request by RLesur**
Pandoc 2.3.1 modified the markdown reader and the HTML writer for autolinks (see https://pandoc.org/releases.html#pandoc-2.3.1-28-september-2018).

This PR integrates these evolutions in the filter `uri-to-fn.lua`.

### CODE REVIEW

**Comment by andreaphsz** [comment]
same issue now for pandoc 2.7.3! will you fix it?

**Comment by RLesur** [comment]
@andreaphsz Thank you very much for the report! 
I haven't tested pandoc 2.7.3 yet. Would it be possible for you to open an issue with a minimal example?  This would help me a lot.

**Comment by andreaphsz** [comment]
Sure, see #111 !

**Comment by RLesur** [comment]
Thanks a lot @andreaphsz !

**Pull request merged**
