### PR TITLE
Wait till PDF is ready (or an error occurs)

### PR DESCRIPTION
**Pull request by yihui**
Following your tip (thanks to @romainfrancois), I managed to make this work. Instead of testing the existence of the PDF file, I test the existence of a token, because the former approach has two problems:

1. I'll have to delete or move the existing PDF file in advance;
2. The PDF file might happen to be incomplete (`writeBin()` hasn't finished writing it).

### CODE REVIEW

**Comment by romainfrancois** [comment]
I’m guessing you meant to mention @RLesur 😀. I’d be happy to help, but I have no idea what 👆means.

**Comment by RLesur** [comment]
@romainfrancois this PR follows my question on Grrr (last night). I just told Yihui that the solution comes from a collective brainstorming with you.

**Comment by romainfrancois** [comment]
Ah ok 🤣 I should have made the connection from the name of the branch.

**Comment by RLesur** [comment]
ht @privefl who also brainstormed with us!

**Pull request merged**
