### PR TITLE
get status code from Network.responseReceived Event.

### PR DESCRIPTION
**Pull request by cderv**
This tries to deal with #66 

The `Network.responseReceived` event from Chrome Devtools Protocol contains the response content, including information from status code. (there is a lots of others informations too!)

This is to show that it works, and stop if status code is above 300.

```r
> chrome_bin <- Sys.getenv("HEADLESS_CHROME")
> pagedown::chrome_print('https://pagedown.rbind.io/html-letter2', verbose = T, browser = chrome_bin)
Message received from headless Chrome: {"method":"Runtime.executionContextCreated","params":{"context":{"id":1,"origin":"://","name":"","auxData":{"isDefault":true,"frameId":"2E48A3FFEB1A7B14E5AD10AF42BFCB98"}}}}
Message received from headless Chrome: {"id":1,"result":{}}
Message received from headless Chrome: {"id":2,"result":{}}
Message received from headless Chrome: {"id":3,"result":{}}
Message received from headless Chrome: {"id":4,"result":{}}
Message received from headless Chrome: {"method":"Network.requestWillBeSent","params":{"requestId":"1FFB09FCDBD3E9AED1D04B436E76BDF3","loaderId":"1FFB09FCDBD3E9AED1D04B436E76BDF3","documentURL":"https://pagedown.rbind.io/html-letter2","request":{"url":"https://pagedown.rbind.io/html-letter2","method":"GET","headers":{"Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/70.0.3508.0 Safari/537.36"},"mixedContentType":"none","initialPriority":"VeryHigh","referrerPolicy":"no-referrer-when-downgrade"},"timestamp":86419.385241,"wallTime":1549650254.187218,"initiator":{"type":"other"},"type":"Document","frameId":"2E48A3FFEB1A7B14E5AD10AF42BFCB98","hasUserGesture":false}}
Message received from headless Chrome: {"method":"Network.responseReceived","params":{"requestId":"1FFB09FCDBD3E9AED1D04B436E76BDF3","loaderId":"1FFB09FCDBD3E9AED1D04B436E76BDF3","timestamp":86419.867971,"type":"Document","response":{"url":"https://pagedown.rbind.io/html-letter2","status":404,"statusText":"","headers":{"status":"404","date":"Fri, 08 Feb 2019 18:24:14 GMT","content-type":"text/html; charset=utf-8","set-cookie":"__cfduid=df880244ab0641b5881d5b2b93e19a0b01549650254; expires=Sat, 08-Feb-20 18:24:14 GMT; path=/; domain=.rbind.io; HttpOnly","cache-control":"public, max-age=0, must-revalidate","x-nf-srv-version":"45aaffea081549dd03a2dfff644cc25cf522edbd","age":"1123","x-nf-request-id":"bb470534-927c-4138-b38a-b2bdc1d77520-25476550","expect-ct":"max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"","server":"cloudflare","cf-ray":"4a6021c9de7db79b-CDG","content-encoding":"gzip"},"mimeType":"text/html","requestHeaders":{":method":"GET",":authority":"pagedown.rbind.io",":scheme":"https",":path":"/html-letter2","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/70.0.3508.0 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","accept-encoding":"gzip, deflate"},"connectionReused":false,"connectionId":10,"remoteIPAddress":"104.31.77.168","remotePort":443,"fromDiskCache":false,"fromServiceWorker":false,"encodedDataLength":383,"timing":{"requestTime":86419.385595,"proxyStart":26.377,"proxyEnd":31.445,"dnsStart":32.261,"dnsEnd":106.31,"connectStart":106.31,"connectEnd":175.317,"sslStart":119.678,"sslEnd":175.286,"workerStart":-1,"workerReady":-1,"sendStart":175.802,"sendEnd":176.099,"pushStart":0,"pushEnd":0,"receiveHeadersEnd":481.714},"protocol":"h2","securityState":"secure","securityDetails":{"protocol":"TLS 1.2","keyExchange":"ECDHE_ECDSA","keyExchangeGroup":"X25519","cipher":"AES_128_GCM","certificateId":0,"subjectName":"sni108475.cloudflaressl.com","sanList":["sni108475.cloudflaressl.com","*.ambercom.co","*.amstournament.com","*.archidamosakridas.tk","*.bookperformance.cf","*.bwinfor.ml","*.cos.name","*.cosx.org","*.daftarhargahp.biz","*.dentistboyntonbeachfl.net","*.drakbardds.com","*.epimitheaszygomalas.tk","*.evinosgiannaris.tk","*.fingerflossing.com","*.handpieceexpress.net","*.hargaku.me","*.hargaku.tech","*.homeopathie-bewustwording.nu","*.howardluksmd.com","*.janeluvsdick.com","*.jerryhan.net","*.k-hdcamreview.ml","*.lazy.sh","*.leonidasleivadas.tk","*.leotychidaslaimos.tk","*.lixy.im","*.maillsender.net","*.meropastomaraioi.tk","*.milfmuetter.com","*.ninjamac.com","*.ninjamac.tech","*.nowteaseme.org","*.orthoinfoguide.com","*.palmvalleywomenscare.com","*.playvid.me","*.podetrazer.com.br","*.rbind.io","*.rbind.org","*.sedgewickeye.com","*.sexyfreereliable.online","*.smashpdfbook.tk","*.taubefamilydental.com","*.yihui.name","*.zelienoplesmiles.com","ambercom.co","amstournament.com","archidamosakridas.tk","bookperformance.cf","bwinfor.ml","cos.name","cosx.org","daftarhargahp.biz","dentistboyntonbeachfl.net","drakbardds.com","epimitheaszygomalas.tk","evinosgiannaris.tk","fingerflossing.com","handpieceexpress.net","hargaku.me","hargaku.tech","homeopathie-bewustwording.nu","howardluksmd.com","janeluvsdick.com","jerryhan.net","k-hdcamreview.ml","lazy.sh","leonidasleivadas.tk","leotychidaslaimos.tk","lixy.im","maillsender.net","meropastomaraioi.tk","milfmuetter.com","ninjamac.com","ninjamac.tech","nowteaseme.org","orthoinfoguide.com","palmvalleywomenscare.com","playvid.me","podetrazer.com.br","rbind.io","rbind.org","sedgewickeye.com","sexyfreereliable.online","smashpdfbook.tk","taubefamilydental.com","yihui.name","zelienoplesmiles.com"],"issuer":"COMODO ECC Domain Validation Secure Server CA 2","validFrom":1548633600,"validTo":1565135999,"signedCertificateTimestampList":[],"certificateTransparencyCompliance":"unknown"}},"frameId":"2E48A3FFEB1A7B14E5AD10AF42BFCB98"}}
Error in execCallbacks(timeoutSecs) : 
  Evaluation error: Evaluation error: Erreur on http status code: 404 returned..
Call `rlang::last_error()` to see a backtrace
```

This surely need adjustment to give informative message and stop nicely.

Does it cover the case of not accessible page for you ?

---
This change is [Reviewable](https://reviewable.io/reviews/rstudio/pagedown/67)

### CODE REVIEW

**Comment by cderv** [comment]
Following a quick discussion with @RLesur , this implementation will also stop the printing process if any resource of the html document is unavailable. 

I tested it with the _html-letter_ and we get 11 resources (html, css, js, gif, png, ...), with the event fired for each. Currently, it will then stop printing if any is not available.

I wanted to give the precision in case we want to deal about that.

**Comment by yihui** [comment]
Yes, I also noticed that. I'll think about what to do. Perhaps give users an option to allow certain failures...

Sorry, I just screwed up something in this PR, which led to an infinite loop (sounds like the web socket is trying to automatically reconnect). I'm trying to figure out what was wrong there.

**Comment by yihui** [comment]
The infinite loop was caused by a wrong id (fixed via 524609c). Now everything seems to work well.

I'm going to merge this now. We can make the decision later on whether to fail on errors of all page resources. I feel it makes sense to fail at least by default, otherwise users don't know the page is actually problematic.

Thank you!

**Comment by antuki** [comment]
It could be a problem with fonts. Is it the reason why I get the "Failed to open https://drees.shinyapps.io/carto-apl/fonts/Lato_700.ttf" ? I don't know very much about it but maybe allowing users to allow some failures could be useful in some cases.

**Comment by yihui** [comment]
I agree it would be useful to have such an option to allow certain resources to fail to load.

Did you really upload `Lato_700.ttf` with your Shiny app?

**Pull request merged**
